### ISSUE TITLE
MonoDETR training

### ISSUE THREAD

**Issue by jskvrna** [skmhrk1209/VSRD#8]
Hi! Thanks for the amazing work.

I would like to ask how you trained the MonoDETR on KITTI-360. Did you convert all your frames from KITTI-360 to KITTI? Do you have a script for that?

Thanks!
Jan

**Comment by skmhrk1209** [comment]
Yes, we converted all the pseudo labels from our custom JSON format to the KITTI format.
[This section](https://github.com/skmhrk1209/VSRD?tab=readme-ov-file#pseudo-label-preparation) in README explains this point. 
Thank you.
